name: WINDOWS RELEASE

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: files

    - name: Package Application
      uses: andrewstech/youtube-dl-server-winbuilder@main
      with:
        path: files
        
          
    - uses: papeloto/action-zip@v1
      with:
        files: files/dist/windows/
        dest: youtube-dl-server.zip

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Windows Build"
        files: youtube-dl-server.zip
